# Generated by Django 4.2 on 2023-05-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
